FROM ubuntu:22.04

COPY src/hello.sh /

# COPY --chmod is supported with buildkit instead of the below instruction
RUN chmod +x /hello.sh

CMD /hello.sh

# META data

ARG SOURCE
ARG REF_NAME
ARG VERSION

LABEL org.opencontainers.image.source "${SOURCE:?}"
LABEL org.opencontainers.image.ref.name "${REF_NAME:?}"
LABEL org.opencontainers.image.version "${VERSION:?}"