FROM ubuntu:22.04

COPY src/hello-bash.sh /

SHELL ["chmod", "+x"]

RUN /hello-bash.sh

SHELL ["/bin/bash", "-c"]

ENTRYPOINT ["/hello-bash.sh"]

CMD ["whoami"]

# META data

ARG SOURCE
ARG REF_NAME
ARG VERSION

LABEL org.opencontainers.image.source "${SOURCE:?}"
LABEL org.opencontainers.image.ref.name "${REF_NAME:?}"
LABEL org.opencontainers.image.version "${VERSION:?}"